# Generated by Django 4.2.4 on 2023-09-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_shopcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productparameter',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='productparameter',
            name='product_info',
        ),
        migrations.DeleteModel(
            name='ConfirmEmailToken',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='ProductParameter',
        ),
    ]
