# Generated by Django 4.2.4 on 2023-09-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_productparameter_parameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='building',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='house',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='structure',
        ),
    ]
