# Generated by Django 4.2.4 on 2023-09-18 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='apartment',
            field=models.CharField(blank=True, max_length=15, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='contact',
            name='building',
            field=models.CharField(blank=True, max_length=15, verbose_name='Строение'),
        ),
        migrations.AddField(
            model_name='contact',
            name='house',
            field=models.CharField(blank=True, max_length=15, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='contact',
            name='structure',
            field=models.CharField(blank=True, max_length=15, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
