# Generated by Django 4.2.4 on 2023-09-18 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_contact_apartment_contact_building_contact_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='apartment',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='building',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Строение'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='house',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='structure',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
