# Generated by Django 4.2.4 on 2023-09-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_order_basket_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='orders',
            new_name='order',
        ),
    ]
