# Generated by Django 4.2.4 on 2023-09-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_basket_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='order',
        ),
        migrations.AddField(
            model_name='basket',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='basket', to='main.order', verbose_name='Заказы'),
        ),
    ]
