# Generated by Django 4.2.4 on 2023-09-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_basket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_info',
        ),
    ]
