# Generated by Django 4.2.4 on 2023-10-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('state', models.CharField(choices=[('Unconfirmed', 'Неподтверждён'), ('Confirmed', 'Подтверждён')], default='unconfirmed')),
            ],
        ),
    ]
