# Generated by Django 4.2.4 on 2023-10-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_emailconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='state',
            field=models.CharField(choices=[('Unconfirmed', 'Неподтверждён'), ('Confirmed', 'Подтверждён')], default='Unconfirmed'),
        ),
    ]
