# Generated by Django 4.2.4 on 2023-10-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_emailconfirmation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
