# Generated by Django 4.2.4 on 2023-10-06 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_rename_basket_listorders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListOrders',
            new_name='Basket',
        ),
    ]
