# Generated by Django 4.2.4 on 2023-10-06 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_rename_listorders_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='orders',
        ),
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='main.order', verbose_name='Продукты'),
        ),
        migrations.CreateModel(
            name='MainOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ManyToManyField(blank=True, null=True, to='main.basket', verbose_name='Мои заказы')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ покупателя',
                'verbose_name_plural': 'Заказы покупателей',
            },
        ),
    ]
