# Generated by Django 4.2.4 on 2023-10-31 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_shop_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='owner',
            new_name='user',
        ),
    ]
