# Generated by Django 4.2.4 on 2023-11-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='model',
        ),
    ]
